apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  version: "1.23"
  name: GroszykMaciejEKS
  region: eu-west-1

managedNodeGroups:
  - name: master
    instanceType: t2.medium
    minSize: 2
    maxSize: 2
    volumeSize: 20
    volumeType: gp2
    labels: {role: master}
    tags:
      nodegroup-role: master
      created_by: Maciej Groszyk
      bootcamp: poland1